//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDetail
    {
        public int ID { get; set; }
        public Nullable<int> BillingBatchID { get; set; }
        public Nullable<int> custID { get; set; }
        public string AgencyName { get; set; }
        public string BillingItem { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string BillingDescription { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> success { get; set; }
    
        public virtual BillingBatch BillingBatch { get; set; }
    }
}
