//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingBatch()
        {
            this.BillingDetails = new HashSet<BillingDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateRan { get; set; }
        public string ByWhom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingDetail> BillingDetails { get; set; }
    }
}
