//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChaseTransaction
    {
        public int Id { get; set; }
        public System.DateTime DateTransaction { get; set; }
        public string Vendor { get; set; }
        public decimal Amount { get; set; }
        public string RefID { get; set; }
        public Nullable<int> CCReqID { get; set; }
        public bool IsReconciled { get; set; }
        public string User { get; set; }
    }
}
