//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckRequestStatusMessage
    {
        public long ID { get; set; }
        public int ReqID { get; set; }
        public Nullable<int> ChkReqID { get; set; }
        public bool Successful { get; set; }
        public string errorMessage { get; set; }
        public string CheckRequestItemDetail { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> BilledToStateStatus { get; set; }
        public Nullable<bool> MakeBillableToClientStatus { get; set; }
        public Nullable<bool> CreateInvoiceStatus { get; set; }
        public Nullable<bool> MarkInvoicePaidStatus { get; set; }
        public Nullable<bool> CreateCheckToPayBillStatus { get; set; }
        public Nullable<bool> MarkCheckToBePrintedStatus { get; set; }
        public Nullable<bool> CheckPrintedStatus { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
