//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckRequest
    {
        public int ID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
        public string PayTo { get; set; }
        public string Purpose { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Agency { get; set; }
        public string CompassUser { get; set; }
        public Nullable<int> custID { get; set; }
        public string custName { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<bool> Success { get; set; }
        public Nullable<bool> SentToAccounting { get; set; }
        public string QBCustomerName { get; set; }
        public string DueDate { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
