//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collector
    {
        public int Id { get; set; }
        public string CollectorName { get; set; }
        public string CollectorSSN { get; set; }
        public System.DateTime DateLastRegistered { get; set; }
        public System.DateTime DateFirstRegistered { get; set; }
        public string Jurisdication { get; set; }
    }
}
