//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditCardRequest
    {
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateToBeRun { get; set; }
        public bool Satisfied { get; set; }
        public string Agency { get; set; }
        public string PayTo { get; set; }
        public string Purpose { get; set; }
        public string ccNumber { get; set; }
        public long serviceItemID { get; set; }
        public string ccAuthorizeNumber { get; set; }
        public string ccUser { get; set; }
        public bool custHasBalance { get; set; }
        public decimal Amount { get; set; }
        public Nullable<bool> transactionError { get; set; }
        public string transactionErrorMessage { get; set; }
        public string UserWhoEntered { get; set; }
        public Nullable<bool> Reconciled { get; set; }
    }
}
