//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSIAutomationEntities : DbContext
    {
        public CSIAutomationEntities()
            : base("name=CSIAutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillingBatch> BillingBatches { get; set; }
        public virtual DbSet<BillingDetail> BillingDetails { get; set; }
        public virtual DbSet<ChaseTransaction> ChaseTransactions { get; set; }
        public virtual DbSet<CheckRequest> CheckRequests { get; set; }
        public virtual DbSet<CheckRequestStatusMessage> CheckRequestStatusMessages { get; set; }
        public virtual DbSet<Collector> Collectors { get; set; }
        public virtual DbSet<CompanyWatchList> CompanyWatchLists { get; set; }
        public virtual DbSet<CompassCustomerName> CompassCustomerNames { get; set; }
        public virtual DbSet<creditCardRequest> creditCardRequests { get; set; }
        public virtual DbSet<CSIQB> CSIQBs { get; set; }
        public virtual DbSet<CustomerDepositBalanceStatic> CustomerDepositBalanceStatics { get; set; }
        public virtual DbSet<ErrorScreenshot> ErrorScreenshots { get; set; }
        public virtual DbSet<IFICompanyName> IFICompanyNames { get; set; }
        public virtual DbSet<IFIQB> IFIQBs { get; set; }
        public virtual DbSet<PDFDataDocsCompositeField> PDFDataDocsCompositeFields { get; set; }
        public virtual DbSet<QBCustomerName> QBCustomerNames { get; set; }
        public virtual DbSet<QBTransaction> QBTransactions { get; set; }
        public virtual DbSet<QBTransactionPull> QBTransactionPulls { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<RequestToUpdateCustomerDepositBalance> RequestToUpdateCustomerDepositBalances { get; set; }
        public virtual DbSet<StateLookup> StateLookups { get; set; }
        public virtual DbSet<StateVendor> StateVendors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
