//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDepositBalanceStatic
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime AsOfDate { get; set; }
    }
}
