//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBCustomerName
    {
        public long ID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
    }
}
