//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBTransaction
    {
        public long ID { get; set; }
        public string CustomerName { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
        public string Num { get; set; }
        public string Memo { get; set; }
        public decimal Amount { get; set; }
        public string theXML { get; set; }
        public string details { get; set; }
        public string InvoiceNum { get; set; }
    }
}
