//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBTransLibrary2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestToUpdateCustomerDepositBalance
    {
        public long ID { get; set; }
        public int custID { get; set; }
        public string CustomerName { get; set; }
        public bool Satisfied { get; set; }
    }
}
